# NumPy for Scientific Computing

#### Documentation - https://numpy.org/devdocs/reference/index.html

In [1]:
import numpy as np

## Matrices

In [2]:
#array of arrays
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.full([3,3],5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [7]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [8]:
matrix = np.array([[1,2,3],[4,5,6]])
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
#transpose
matrix.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## Mathematical Operations

In [10]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

In [11]:
x+y

array([[ 6,  8],
       [10, 12]])

In [12]:
x-y

array([[-4, -4],
       [-4, -4]])

In [13]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [14]:
#element wise multiplication
x*y 

array([[ 5, 12],
       [21, 32]])

In [15]:
# dot product
x.dot(y)

array([[19, 22],
       [43, 50]])

In [16]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [17]:
x.sum()

10

In [18]:
x.sum(axis=0)
#sum about columns

array([4, 6])

In [19]:
x.sum(axis=1)
#sum about rows

array([3, 7])

In [20]:
x.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [21]:
#-1 lets the computer decide the correct dimension
x.reshape(-1,4)

array([[1, 2, 3, 4]])

## Concatination

In [22]:
np.stack((x,y))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [23]:
np.hstack((x,y))
#horiontal stack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [24]:
np.vstack((x,y))
#vertical stack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

## Random Module

In [25]:
np.random.rand(3,3)

array([[0.50955187, 0.15945598, 0.76008394],
       [0.85622566, 0.75443949, 0.49115353],
       [0.72102572, 0.70828458, 0.68681023]])

In [26]:
#normal distribution
np.random.randn(3,3)

array([[ 2.24658946,  0.54225689, -0.34845592],
       [-0.5990801 ,  0.67116169,  2.00791511],
       [-0.71106281,  2.09271672, -1.60073229]])

In [27]:
np.random.seed(5)
#seed stores the state
#returns same numbers generated the first time it was run
np.random.rand(5,5)

array([[0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119],
       [0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123],
       [0.08074127, 0.7384403 , 0.44130922, 0.15830987, 0.87993703],
       [0.27408646, 0.41423502, 0.29607993, 0.62878791, 0.57983781],
       [0.5999292 , 0.26581912, 0.28468588, 0.25358821, 0.32756395]])

In [28]:
np.random.random(5)

array([0.1441643 , 0.16561286, 0.96393053, 0.96022672, 0.18841466])

In [29]:
np.random.randint(5,15,5)

array([14,  8,  8,  7,  6])

In [30]:
arr = np.arange(10)

In [31]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.random.shuffle(arr)

In [33]:
arr

array([2, 1, 0, 6, 3, 9, 8, 4, 7, 5])

In [34]:
np.random.choice(arr)

4

## Statistical Functions

In [35]:
a = np.array([[1,5,2,3],[9,0,3,9]])
a

array([[1, 5, 2, 3],
       [9, 0, 3, 9]])

In [36]:
np.min(a)

0

In [37]:
np.min(a, axis=0)

array([1, 0, 2, 3])

In [38]:
np.max(a)

9

In [39]:
np.max(a, axis=1)

array([5, 9])

In [40]:
np.mean(a)

4.0

In [41]:
np.mean(a,axis=1)

array([2.75, 5.25])

In [42]:
b = [1,5,2,9,9]
w = [1,9,3,3,5]

np.average(b, weights=w)

5.904761904761905

In [43]:
np.median(a)

3.0

In [44]:
np.median(a,axis=1)

array([2.5, 6. ])

In [45]:
np.std(a)

3.2015621187164243

In [46]:
np.var(a)

10.25

## Norm

In [47]:
v = np.array([2,5,6])

In [48]:
np.linalg.norm(v)

8.06225774829855

In [49]:
np.linalg.norm(v, ord=1)
# L1 returns sum of elements

13.0

In [50]:
np.linalg.norm(v, ord=np.inf)
#L(inf) returns the highest number

6.0

## Broadcasting

In [51]:
array = np.arange(120).reshape(5,3,2,4)

In [52]:
array

array([[[[  0,   1,   2,   3],
         [  4,   5,   6,   7]],

        [[  8,   9,  10,  11],
         [ 12,  13,  14,  15]],

        [[ 16,  17,  18,  19],
         [ 20,  21,  22,  23]]],


       [[[ 24,  25,  26,  27],
         [ 28,  29,  30,  31]],

        [[ 32,  33,  34,  35],
         [ 36,  37,  38,  39]],

        [[ 40,  41,  42,  43],
         [ 44,  45,  46,  47]]],


       [[[ 48,  49,  50,  51],
         [ 52,  53,  54,  55]],

        [[ 56,  57,  58,  59],
         [ 60,  61,  62,  63]],

        [[ 64,  65,  66,  67],
         [ 68,  69,  70,  71]]],


       [[[ 72,  73,  74,  75],
         [ 76,  77,  78,  79]],

        [[ 80,  81,  82,  83],
         [ 84,  85,  86,  87]],

        [[ 88,  89,  90,  91],
         [ 92,  93,  94,  95]]],


       [[[ 96,  97,  98,  99],
         [100, 101, 102, 103]],

        [[104, 105, 106, 107],
         [108, 109, 110, 111]],

        [[112, 113, 114, 115],
         [116, 117, 118, 119]]]])

In [53]:
array * np.arange(8).reshape(2,4)

array([[[[  0,   1,   4,   9],
         [ 16,  25,  36,  49]],

        [[  0,   9,  20,  33],
         [ 48,  65,  84, 105]],

        [[  0,  17,  36,  57],
         [ 80, 105, 132, 161]]],


       [[[  0,  25,  52,  81],
         [112, 145, 180, 217]],

        [[  0,  33,  68, 105],
         [144, 185, 228, 273]],

        [[  0,  41,  84, 129],
         [176, 225, 276, 329]]],


       [[[  0,  49, 100, 153],
         [208, 265, 324, 385]],

        [[  0,  57, 116, 177],
         [240, 305, 372, 441]],

        [[  0,  65, 132, 201],
         [272, 345, 420, 497]]],


       [[[  0,  73, 148, 225],
         [304, 385, 468, 553]],

        [[  0,  81, 164, 249],
         [336, 425, 516, 609]],

        [[  0,  89, 180, 273],
         [368, 465, 564, 665]]],


       [[[  0,  97, 196, 297],
         [400, 505, 612, 721]],

        [[  0, 105, 212, 321],
         [432, 545, 660, 777]],

        [[  0, 113, 228, 345],
         [464, 585, 708, 833]]]])

In [54]:
array * np.arange(24).reshape(3,2,4)

array([[[[   0,    1,    4,    9],
         [  16,   25,   36,   49]],

        [[  64,   81,  100,  121],
         [ 144,  169,  196,  225]],

        [[ 256,  289,  324,  361],
         [ 400,  441,  484,  529]]],


       [[[   0,   25,   52,   81],
         [ 112,  145,  180,  217]],

        [[ 256,  297,  340,  385],
         [ 432,  481,  532,  585]],

        [[ 640,  697,  756,  817],
         [ 880,  945, 1012, 1081]]],


       [[[   0,   49,  100,  153],
         [ 208,  265,  324,  385]],

        [[ 448,  513,  580,  649],
         [ 720,  793,  868,  945]],

        [[1024, 1105, 1188, 1273],
         [1360, 1449, 1540, 1633]]],


       [[[   0,   73,  148,  225],
         [ 304,  385,  468,  553]],

        [[ 640,  729,  820,  913],
         [1008, 1105, 1204, 1305]],

        [[1408, 1513, 1620, 1729],
         [1840, 1953, 2068, 2185]]],


       [[[   0,   97,  196,  297],
         [ 400,  505,  612,  721]],

        [[ 832,  945, 1060, 1177],
         [1296, 1417,

## Mesh Grid

In [64]:
c = [1,2,3]
d=[4,5,6,7]

In [65]:
c,d = np.meshgrid(c,d)

In [66]:
print(c)
print(d)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
[[4 4 4]
 [5 5 5]
 [6 6 6]
 [7 7 7]]
